print("Enter First number =\t")
a = input()
print("Enter second number =\t")
b=input()
# print("Sum= ", int(a)+int(b))
# print("Subtarction= ", int(a)-int(b))
# print("Multiplaction= ", int(a)*int(b))
# print("Division= ", int(a)/int(b))
print("Sum=",int(a)+int(b),"\nSubtract=",int(a)-int(b),"\nMultiplication=",int(a)*int(b),"\nDivision=",int(a)/int(b))